import React, { ReactElement } from 'react';
import Auth from '../layouts/Auth';
import NextPageWithLayout from '../layouts/NextPageWithLayout';
import Image from 'next/image';
import Head from 'next/head';
import Landing from '../layouts/Landing';

const Faq: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Sitecore/Opti Hackathon: Frequeytly Asked Questions</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="container mx-auto px-4 h-full">
                <div className="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg mt-16">
                    <div className="py-20 dark:bg-gray-600 rounded-lg">
                        <h1 className="text-4xl text-center text-gray-700 dark:text-gray-50 font-extrabold">Frequently Asked Questions</h1>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 md:mx-40 mx-4 mt-20">
                            <div className="text-gray-800 dark:text-gray-50 bg-gray-100 dark:bg-gray-700 rounded-md p-4">
                                <h2 className="text-md font-semibold">Do I need to know React, TypeScript, and Next.js to participate?</h2>
                                <p className="text-sm mt-4 font-light leading-6">No! You can use this as an opportunity to learn, or familiarize yourself ahead of time a little. TypeScript is not required for this, but React and Next.js are.</p>
                            </div>
                            <div className="text-gray-800 dark:text-gray-50 bg-gray-100 dark:bg-gray-700 rounded-md p-4">
                                <h2 className="text-md font-semibold">Do I need a team? How do I find teammates?</h2>
                                <p className="text-sm mt-4 font-light leading-6">You don’t have to have a team, but feel free to sign up as a solo entry and indicate you are interested in being part of a team– we will email all the solo entries and then try to figure things out.</p>
                            </div>
                            <div className="text-gray-800 dark:text-gray-50 bg-gray-100 dark:bg-gray-700 rounded-md p-4">
                                <h2 className="text-md font-semibold">What are the prizes?</h2>
                                <p className="text-sm mt-4 font-light leading-6">TBD based on how many people sign up – maybe everyone is a winner!</p>
                            </div>
                            <div className="text-gray-800 dark:text-gray-50 bg-gray-100 dark:bg-gray-700 rounded-md p-4">
                                <h2 className="text-md font-semibold">Do I have to build something valuable to the company?</h2>
                                <p className="text-sm mt-4 font-light leading-6">No!</p>
                            </div>

                            <div className="text-gray-800 dark:text-gray-50 bg-gray-100 dark:bg-gray-700 rounded-md p-4">
                                <h2 className="text-md font-semibold">Will you make fun of my app if it is just a button and a textbox?</h2>
                                <p className="text-sm mt-4 font-light leading-6">Next question...</p>
                            </div>

                            <div className="text-gray-800 dark:text-gray-50 bg-gray-100 dark:bg-gray-700 rounded-md p-4">
                                <h2 className="text-md font-semibold">What’s in it for <strong>me</strong>? </h2>
                                <p className="text-sm mt-4 font-light leading-6">The joy of learning, comradery, and one (1) meal on us.† Possibly prizes!</p>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-1 gap-10 md:mx-40 mx-4 mt-20">
                            <p className="mb-4 text-lg leading-relaxed text-white">
                                † Perficient T&M Expense policy applies ($25 maximum, itemized receipt)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

Faq.getLayout = function getLayout(page: ReactElement) {
    return (
        <Landing>{page}</Landing>
    )
}

export default Faq;