import React, { ReactElement } from 'react';
import Auth from '../layouts/Auth';
import NextPageWithLayout from '../layouts/NextPageWithLayout';
import Image from 'next/image';
import Head from 'next/head';
import Landing from '../layouts/Landing';

const Teams: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Sitecore/Opti Hackathon: Teams</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="container mx-auto px-4 h-full">
                <div className="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg mt-16">
                    <div className="px-6">
                        <div className="text-center mt-12">
                            <h1 className="text-xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
                                Sitecore/Opti Hackathon Registered Teams
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

Teams.getLayout = function getLayout(page: ReactElement) {
    return (
        <Landing>{page}</Landing>
    )
}

export default Teams;